# Build and push the Docker image for Gitpod
# - Only pushes if push or release
# - Builds without push for PRs to check the Dockerfile

name: Build Gitpod Docker image

on:
  pull_request:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  push_to_registry:
    if: github.repository == 'nextflow-io/training'
    name: Build + Push Gitpod Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build / push latest image
        uses: docker/build-push-action@v5
        if: github.event_name != 'release'
        with:
          file: .github/gitpod.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/nextflow-io/training:latest

      - name: Push release image
        uses: docker/build-push-action@v5
        if: github.event_name == 'release'
        with:
          file: .github/gitpod.Dockerfile
          push: true
          tags: ghcr.io/nextflow-io/training:${{ github.event.release.tag_name }}
