# Build and push the Docker image for building the site (mkdocs material)

name: Build mkdocs docker image

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mkdocs_docker:
    if: github.repository == 'nextflow-io/training'
    name: Build + push mkdocs docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build / push latest image
        uses: docker/build-push-action@v5
        with:
          file: .github/mkdocs.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/nextflow-io/training-mkdocs:latest
